"""Paper overlay readiness aggregation.

This module summarizes paper execution observations for environment
calibration. It does not validate alpha, promote strategies, place orders, or
write production execution parameters.
"""

from __future__ import annotations

import csv
from dataclasses import dataclass
import json
from pathlib import Path
from typing import Any, Sequence

import pandas as pd


SUMMARY_ARTIFACT = "paper_overlay_calibration_summary.json"
LATENCY_BUCKETS_ARTIFACT = "paper_overlay_latency_buckets.csv"
SPREAD_CAPTURE_ARTIFACT = "paper_overlay_spread_capture.csv"
READINESS_ARTIFACT = "paper_overlay_readiness.md"


@dataclass(frozen=True)
class PaperOverlayReadinessResult:
    """Readiness summary and tabular diagnostics for paper overlay calibration."""

    summary: dict[str, Any]
    latency_buckets: list[dict[str, Any]]
    spread_capture: list[dict[str, Any]]


def assess_paper_overlay_readiness(
    *,
    observations: pd.DataFrame,
    requested_sample_count: int = 50,
    max_validated_participation_rate: float = 0.001,
) -> PaperOverlayReadinessResult:
    """Aggregate local paper observations into a paper-overlay readiness record."""

    if requested_sample_count <= 0:
        raise ValueError("requested_sample_count must be positive")
    if max_validated_participation_rate <= 0.0:
        raise ValueError("max_validated_participation_rate must be positive")

    frame = observations.copy()
    if frame.empty:
        raise ValueError("observations cannot be empty")
    _require_columns(
        frame,
        {
            "ticker",
            "requested_qty",
            "filled_qty",
            "spread_bps",
            "half_spread_bps",
            "drift_bps",
            "drift_vs_half_spread",
            "capture_to_submit_latency_seconds",
            "time_of_day_bucket",
        },
    )
    frame["ticker"] = frame["ticker"].astype(str).str.strip().str.upper()
    for column in (
        "requested_qty",
        "filled_qty",
        "spread_bps",
        "half_spread_bps",
        "drift_bps",
        "drift_vs_half_spread",
        "capture_to_submit_latency_seconds",
    ):
        frame[column] = pd.to_numeric(frame[column], errors="coerce")
    frame = frame.dropna(
        subset=[
            "ticker",
            "requested_qty",
            "filled_qty",
            "spread_bps",
            "drift_bps",
            "capture_to_submit_latency_seconds",
        ]
    ).copy()
    if frame.empty:
        raise ValueError("observations contain no complete paper overlay rows")

    latency_buckets = _latency_bucket_rows(frame)
    spread_capture = _spread_capture_rows(frame)
    observation_count = int(len(frame))
    summary = {
        "scope": "paper_overlay_execution_environment_calibration_only",
        "alpha_promotion_allowed": False,
        "production_config_update_allowed": False,
        "live_alpha_orders_allowed": False,
        "requested_sample_count": int(requested_sample_count),
        "observation_count": observation_count,
        "readiness_status": "sufficient" if observation_count >= int(requested_sample_count) else "needs_more_samples",
        "max_validated_participation_rate": float(max_validated_participation_rate),
        "median_latency_seconds": _median(frame["capture_to_submit_latency_seconds"]),
        "median_drift_bps": _median(frame["drift_bps"]),
        "median_spread_bps": _median(frame["spread_bps"]),
        "noise_floor_bps": _iqr(frame["drift_bps"]),
        "staleness_bias_bps": _staleness_bias(frame),
        "paper_venue_quirk_note": "Paper fills are venue-simulation observations and must not be treated as alpha validation.",
    }
    return PaperOverlayReadinessResult(
        summary=summary,
        latency_buckets=latency_buckets,
        spread_capture=spread_capture,
    )


def render_paper_overlay_readiness_markdown(result: PaperOverlayReadinessResult) -> str:
    """Render a concise paper-overlay readiness note."""

    summary = result.summary
    lines = [
        "# Paper Overlay Readiness",
        "",
        "This artifact is execution environment calibration only. It does not validate alpha, promote strategies, or approve live alpha orders.",
        "",
        "## Scope",
        "",
        f"- readiness_status: `{summary['readiness_status']}`",
        f"- observation_count: `{summary['observation_count']}`",
        f"- requested_sample_count: `{summary['requested_sample_count']}`",
        f"- max_validated_participation_rate: `{summary['max_validated_participation_rate']}`",
        "- No live alpha orders are generated by this readiness lane.",
        "- Calibrated parameters are not pushed into production configs.",
        "",
        "## Bias / Noise / Venue",
        "",
        f"- staleness_bias_bps: `{summary['staleness_bias_bps']}`",
        f"- noise_floor_bps: `{summary['noise_floor_bps']}`",
        f"- paper_venue_quirk_note: {summary['paper_venue_quirk_note']}",
        "",
        "## Latency Buckets",
        "",
        "| bucket | count | median_latency_seconds | median_drift_bps | median_spread_bps |",
        "|---|---:|---:|---:|---:|",
    ]
    for row in result.latency_buckets:
        lines.append(
            f"| {row['time_of_day_bucket']} | {row['observation_count']} | "
            f"{row['median_latency_seconds']} | {row['median_drift_bps']} | {row['median_spread_bps']} |"
        )
    return "\n".join(lines) + "\n"


def write_paper_overlay_readiness_artifacts(
    result: PaperOverlayReadinessResult,
    output_dir: str | Path,
) -> dict[str, Path]:
    """Write the standard Phase 40 local artifact set."""

    resolved_output_dir = Path(output_dir)
    resolved_output_dir.mkdir(parents=True, exist_ok=True)
    artifacts = {
        SUMMARY_ARTIFACT: resolved_output_dir / SUMMARY_ARTIFACT,
        LATENCY_BUCKETS_ARTIFACT: resolved_output_dir / LATENCY_BUCKETS_ARTIFACT,
        SPREAD_CAPTURE_ARTIFACT: resolved_output_dir / SPREAD_CAPTURE_ARTIFACT,
        READINESS_ARTIFACT: resolved_output_dir / READINESS_ARTIFACT,
    }
    artifacts[SUMMARY_ARTIFACT].write_text(_dump_json(result.summary), encoding="utf-8")
    _write_csv(
        artifacts[LATENCY_BUCKETS_ARTIFACT],
        result.latency_buckets,
        [
            "time_of_day_bucket",
            "observation_count",
            "median_latency_seconds",
            "median_drift_bps",
            "median_spread_bps",
        ],
    )
    _write_csv(
        artifacts[SPREAD_CAPTURE_ARTIFACT],
        result.spread_capture,
        [
            "ticker",
            "observation_count",
            "median_spread_bps",
            "median_half_spread_bps",
            "median_drift_vs_half_spread",
        ],
    )
    artifacts[READINESS_ARTIFACT].write_text(render_paper_overlay_readiness_markdown(result), encoding="utf-8")
    return artifacts


def _latency_bucket_rows(frame: pd.DataFrame) -> list[dict[str, Any]]:
    grouped = (
        frame.groupby("time_of_day_bucket", dropna=False)
        .agg(
            observation_count=("ticker", "size"),
            median_latency_seconds=("capture_to_submit_latency_seconds", "median"),
            median_drift_bps=("drift_bps", "median"),
            median_spread_bps=("spread_bps", "median"),
        )
        .reset_index()
        .sort_values("time_of_day_bucket")
    )
    return [_round_numeric_row(row) for row in grouped.to_dict(orient="records")]


def _spread_capture_rows(frame: pd.DataFrame) -> list[dict[str, Any]]:
    grouped = (
        frame.groupby("ticker", dropna=False)
        .agg(
            observation_count=("ticker", "size"),
            median_spread_bps=("spread_bps", "median"),
            median_half_spread_bps=("half_spread_bps", "median"),
            median_drift_vs_half_spread=("drift_vs_half_spread", "median"),
        )
        .reset_index()
        .sort_values("ticker")
    )
    return [_round_numeric_row(row) for row in grouped.to_dict(orient="records")]


def _staleness_bias(frame: pd.DataFrame) -> float:
    latency = frame["capture_to_submit_latency_seconds"]
    drift = frame["drift_bps"]
    if len(frame) < 2 or float(latency.max()) == float(latency.min()):
        return 0.0
    slow = drift.loc[latency >= latency.median()]
    fast = drift.loc[latency < latency.median()]
    if slow.empty or fast.empty:
        return 0.0
    return round(float(slow.median() - fast.median()), 12)


def _median(series: pd.Series) -> float:
    return round(float(pd.to_numeric(series, errors="coerce").dropna().median()), 12)


def _iqr(series: pd.Series) -> float:
    clean = pd.to_numeric(series, errors="coerce").dropna()
    if clean.empty:
        return 0.0
    return round(float(clean.quantile(0.75) - clean.quantile(0.25)), 12)


def _round_numeric_row(row: dict[str, Any]) -> dict[str, Any]:
    cleaned: dict[str, Any] = {}
    for key, value in row.items():
        if isinstance(value, float):
            cleaned[key] = round(value, 12)
        else:
            cleaned[key] = value
    return cleaned


def _require_columns(frame: pd.DataFrame, required: set[str]) -> None:
    missing = sorted(required.difference(frame.columns))
    if missing:
        raise ValueError("observations missing required columns: " + ", ".join(missing))


def _write_csv(path: Path, rows: Sequence[dict[str, Any]], columns: Sequence[str]) -> None:
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(columns))
        writer.writeheader()
        for row in rows:
            writer.writerow({column: row.get(column, "") for column in columns})


def _dump_json(payload: dict[str, Any]) -> str:
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"
